### ISSUE TITLE
quitar pyabacus de requirements.txt

### ISSUE THREAD

**Issue by daguzman35** [Tausand-dev/TempicoSoftware#33]
En rama 'FLIMtest' encuentro que en requirements.txt está PyAbacus. Eliminar dependencias asociadas con PyAbacus y/o con AbacusSoftware.

**Comment by JoanAmaya** [comment]
La rama a descargar es FLIMtest anteriormente me fije que había una rama llamada FLIMTest ahora paso a llamarse FLIMoldTest con el fin de no generar confusión. En esta rama se corrige pyabacus
