### ISSUE TITLE
falta SciPy en requirements

### ISSUE THREAD

**Issue by daguzman35** [Tausand-dev/TempicoSoftware#34]
Usando rama 'FLIMtest', compilándola en Windows 7 32-bit, usando Python 3.8.10, creando venv: se encuentra que falta Scipy. Por esta razón no se puede ejecutar el software.

Tras haber instalado los requirements en un ambiente virtual, y tras ejecutar     `python main.py`, la línea de comandos retorna siguiente mensaje de error:

> (.venv2024oct) C:\Users\David\Desktop\TS 2024-10\TempicoSoftware-FLIMTest>python main.py 
> Error occurred while creating the folder and/or file: [Errno 13] Permission denied: 'C:\\Users\\David\\Documents\\TempicoSoftwareData\\data_constants.txt'
> Traceback (most recent call last):
>   File "main.py", line 43, in <module>
>   File "C:\Users\David\Desktop\TS 2024-10\TempicoSoftware-FLIMTest\.venv2024oct\
> Lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 146,
>  in _import
>   File "C:\Users\David\Desktop\TS 2024-10\TempicoSoftware-FLIMTest\FLIMGraphics.
> py", line 10, in <module>
>   File "C:\Users\David\Desktop\TS 2024-10\TempicoSoftware-FLIMTest\.venv2024oct\
> Lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 146,
>  in _import
> ModuleNotFoundError: No module named 'scipy'
> 

Notar que además de no encontrar scipy, tampoco puede escribir archivos.

**Comment by daguzman35** [comment]
Comentario adicional: he creado ejecutable en Windows 7 32-bit, Python 3.8.10. Se genera un exe de 79.4MB. Al ejecutar el exe generado, entrega el siguiente mensaje de error, acorde con el error reportado (falta Scipy).

![Image](https://github.com/user-attachments/assets/ccaa932d-7da9-4abf-bf91-bd0ba3ecc3cf)

**Comment by JoanAmaya** [comment]
Se añade scipy en requirements.txt con el siguiente atributo con el fin de que no se generen fallas en sistemas de 32 bits
scipy==1.9.1 --only-binary=:all:

**Comment by daguzman35** [comment]
Se genera issue #37, que ya solucioné.
Queda aún por probar software, porque no he podido ejecutarlo por issue #40.
