### ISSUE TITLE
Linux: no lista dispositivos conectados

### ISSUE THREAD

**Issue by daguzman35** [Tausand-dev/TempicoSoftware#45]
v1.0.0
Al ejecutar TempicoSoftware en Linux, este no reconoce los dispositivos conectados. Probado usando Python 3.8.20 en Ubuntu 64-bits.

Probar y corregir tanto en Linux como en Mac.

Al usar librería PyTempico 1.0.0 en Linux, sí funcionan los comandos de comunicación con el dispositivo.

Pantallazo de diálogo inicial en Linux:

![Image](https://github.com/user-attachments/assets/873f19ae-2e7d-47e6-b0df-093bb3f7c687)

Pantallazos adicionales versión Linux ejecutada:
![Image](https://github.com/user-attachments/assets/e3f00c13-f24d-45d0-a0ee-51a0ae315134)
![Image](https://github.com/user-attachments/assets/0e471da3-aa07-4f85-b869-c8c8c2d84685)

**Comment by JoanAmaya** [comment]
Es un error al no considerar que en linux no se muestran ciertos parametros que en windows si, se actualiza teniendo en cuenta que los puertos de S.O linux like se guardan en las rutas /dev/ y se debe obtener el device de hid api mas no el name.
