### ISSUE TITLE
v1.0.0 start-stop: medidas '-1' en canales B, C, D.

### ISSUE THREAD

**Issue by daguzman35** [Tausand-dev/TempicoSoftware#46]
v1.0.0 con Tempico TP1004-1.2
Software registra medidas en canales B, C y D con valor '-1' siempre. No registra ningún valor correcto (ninguno es positivo).
Canal A funciona correctamente.

**Comment by daguzman35** [comment]
Probado conectando en canales start, A, B, C y D señales de 31250Hz. 

Usando software v1.0.0 en Windows.

Archivos obtenidos:

[histogram_data20241128105308channelA.txt](https://github.com/user-attachments/files/17950556/histogram_data20241128105308channelA.txt)
[histogram_data20241128105308channelB.txt](https://github.com/user-attachments/files/17950557/histogram_data20241128105308channelB.txt)
[histogram_data20241128105308channelC.txt](https://github.com/user-attachments/files/17950559/histogram_data20241128105308channelC.txt)
[histogram_data20241128105308channelD.txt](https://github.com/user-attachments/files/17950558/histogram_data20241128105308channelD.txt)

notar que archivos B,C,D almacenan solo '-1'.

Gráficas obtenidas:
![Image](https://github.com/user-attachments/assets/9c96efe0-eb00-4de1-8fa6-d2dc4e077b29)
![Image](https://github.com/user-attachments/assets/31ef0440-98f9-4a26-9d58-5883e61b71f1)
![Image](https://github.com/user-attachments/assets/0da79c7b-ceed-413e-8435-494fd4c377b3)
![Image](https://github.com/user-attachments/assets/b7f602d1-0b8b-4308-a0c2-9cb962006497)

**Comment by JoanAmaya** [comment]
Se trata de un problema de lógica que ya había sido arreglado en otras ramas, actualicé el main y quedo corregido el error
